# Gambas Action File 3.0

{ Actions
  { Action about
    Text = "About this program"
    Picture = "icon:/32/question"
  }
  { Action cadArc
    Text = ""
    Picture = "$ToolButton"
  }
  { Action cadPan
    Text = "Pan drawing"
    Picture = "$ToolButton"
  }
  { Action cadSlab
    Text = ""
    Picture = "$ToolButton"
  }
  { Action cadZoomW
    Text = "Zoom to a defined window"
    Picture = "$ToolButton"
  }
  { Action cadZoome
    Text = "Zoom to view all drawing"
    Picture = "$ToolButton"
  }
  { Action cadellipse
    Text = ""
    Picture = "$ToolButton"
  }
  { Action cadlayers
    Text = "Layer table"
    Picture = "icon:/32/menu"
  }
  { Action cadleader
    Text = ""
    Picture = "$ToolButton"
  }
  { Action cadline
    Text = ""
    Picture = "$ToolButton"
  }
  { Action cadlwpolyline
    Text = ""
    Picture = "$ToolButton"
  }
  { Action cadpolygon
    Text = ""
    Picture = "$ToolButton"
  }
  { Action cadsolid
    Text = ""
    Picture = "$ToolButton"
  }
  { Action cofee
    Text = "Buy me a cofee!!!"
    Picture = "png/buymeacofee32.png"
  }
  { Action config
    Text = ""
    Picture = "icon:/32/options"
  }
  { Action dimstyle_change
    Text = ""
    Picture = "$ComboBox"
  }
  { Action exit
    Text = ""
    Picture = "icon:/32/quit"
  }
  { Action file_new
    Text = ""
    Picture = "icon:/32/new"
  }
  { Action file_open
    Text = ""
    Picture = "icon:/32/open"
  }
  { Action file_save
    Text = ""
    Picture = "icon:/32/save"
  }
  { Action file_saveas
    Text = ""
    Picture = "icon:/32/save-as"
  }
  { Action print
    Text = ""
    Picture = "icon:/32/print"
  }
  { Action redo
    Text = ""
    Picture = "icon:/32/redo"
  }
  { Action undo
    Text = ""
    Picture = "icon:/32/undo"
  }
}

